import { ThemeProvider } from '@mui/material';
import './globals.css'
import theme from '../lib/theme';
import ThemeRegistry from '@/components/ThemeRegistry';
import { Outfit } from 'next/font/google';
const outfit = Outfit({
    subsets: ['latin'],
    display: 'swap', // Font yüklenirken fallback göster, sonra değiştir
    variable: '--font-outfit', // CSS değişkeni oluştur (opsiyonel ama kullanışlı)
  });
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" >

      <body>
        <ThemeRegistry>
        {children}
        </ThemeRegistry>
        </body>
    </html>
  )
}
