'use client'
import React from 'react';
import { ThemeProvider } from '@mui/material';
import '../app/globals.css'

import theme from '../lib/theme';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function ThemeRegistry({ children }) {
  return (
    <html lang="en" >

      <body >
        <ThemeProvider theme={theme}>
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
